version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=videos
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 6033:80
    environment:
      - PMA_ARBITRARY=1
  app:
    container_name: app
    volumes:
      - c:/data:app/VideoLocalManager/app/data
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8000:8000