version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=videos
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 6033:80
    environment:
      - PMA_ARBITRARY=1
  app:
    container_name: app
    networks:
      app_net:
        ipv4_address: 192.168.1.57
    volumes:
      - c:/data:/app/data/
    ports:
      - 8000:8000
    depends_on: 
      - "mysql"
    entrypoint: ./wait-for-it.sh mysql:3306 -t 0 -- go run db_connection.go video.go feedDB.go main.go
    build:
      context: app
      dockerfile: Dockerfile 
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24
        #gateway: 192.168.1.254